#!/bin/bash

source app/functions

# Set the default application path

function applicationPath() {
    
    APPLICATION_PATH_DEFAULT='/var/www/html'
    echo -n "What is the location of your PrestaShop installation? [$APPLICATION_PATH_DEFAULT] "
    read APPLICATION_PATH
    
    APPLICATION_PATH=${APPLICATION_PATH:-$APPLICATION_PATH_DEFAULT}
    if [[ ! -d $APPLICATION_PATH ]]; then
        warning "$APPLICATION_PATH is not a directory"
        applicationPath
    else
        echo "APPLICATION_PATH=$APPLICATION_PATH" >> .env
        success "Using PrestaShop installation path: $APPLICATION_PATH"
    fi    
}
