#!/bin/bash

source app/functions

# Database user

function databaseUser() {

    DATABASE_USER_DEFAULT=$(detectDatabaseParam 'database_user')
    echo -n "What is the database user? [$DATABASE_USER_DEFAULT]"
    read DATABASE_USER
    DATABASE_USER=${DATABASE_USER:-$DATABASE_USER_DEFAULT}
    
     echo "DATABASE_USER=$DATABASE_USER" >> .env
     success "Database user is set to $DATABASE_USER"
}
