#!/bin/bash

source app/functions

# Set database connection

function databaseCredentials() {
    databaseHost

    databaseName

    databaseUser

    databasePassword

    databasePrefix

    mysql -h $DATABASE_HOST -u $DATABASE_USER -p$DATABASE_PASSWORD $DATABASE_NAME -e "SELECT * FROM ${DATABASE_PREFIX}configuration LIMIT 1"

    if [[ $? != 0 ]]; then
        warning "Could not connect to the database"
        
        databaseCredentials
    fi
}
