#!/bin/bash

source app/functions

function databasePassword() {

    # Database password
    DATABASE_PASSWORD_DEFAULT=$(detectDatabaseParam 'database_password')
    echo -n "What is the database password? [$DATABASE_PASSWORD_DEFAULT]"
    read DATABASE_PASSWORD
    DATABASE_PASSWORD=${DATABASE_PASSWORD:-$DATABASE_PASSWORD_DEFAULT}
    
    # echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
    # success "Database password is set to $DATABASE_PASSWORD"
}
