#!/bin/bash

source app/functions

# Was the setup already done?

function newsetup() {

    if [[ -f .env ]]; then
        DO_SETUP_AGAIN_DEFAULT=yes
        echo -n "Setup was already completed, are you sure you want to do it again? [yes/no, default yes]"
        read DO_SETUP_AGAIN
        DO_SETUP_AGAIN=${DO_SETUP_AGAIN:-$DO_SETUP_AGAIN_DEFAULT}

        if [[ $DO_SETUP_AGAIN == 'yes' ]]; then
            rm .env
            success ".env file is deleted"
        else
            echo "Setup is cancelled."
            exit 1;
        fi
    fi
}
