#!/bin/bash

source app/functions

# Get prefered upgrade version

function newVersion() {
    echo -n "Which version of PrestaShop you want to upgrade to?"
    read PRESTASHOP_NEW_VERSION
    url="https://github.com/PrestaShop/PrestaShop/releases/tag/$PRESTASHOP_NEW_VERSION"
    http_code=$(curl -o /dev/null -s -w "%{http_code}" "$url")
    if [[ $http_code -ge 200 && $http_code -lt 300 ]]; then
        success "This version is available"
    else
        warning "This versiion is not available, pick another version"
        newVersion
    fi

    echo "PRESTASHOP_NEW_VERSION=$PRESTASHOP_NEW_VERSION" >> .env
    success "PrestaShop new version: '$PRESTASHOP_NEW_VERSION'"
}
