#!/bin/bash

source app/functions

function publicUrl() {

    # Set shop url
    SHOP_URL_DEFAULT='http://localhost'
    echo -n "What is shop URL? [$SHOP_URL_DEFAULT] "
    read SHOP_URL
    SHOP_URL=${SHOP_URL:-$SHOP_URL_DEFAULT}
    echo "SHOP_URL=$SHOP_URL" >> .env
    http_code=$(curl -o /dev/null -s -w "%{http_code}\n" $SHOP_URL)
    # Check if the status code is outside of the 2xx and 3xx range
    if [[ $http_code -lt 200 || $http_code -ge 400 ]]; then
        warning "The URL provides a response code is outside of the 2xx and 3xx range: $http_code"
        publicUrl
    else
        success "The URL provides a response code is within the 2xx or 3xx range: $http_code"
    fi
}
