#!bin/bash

# Colors
WARNING='\033[1;33m'
SUCCESS='\033[1;32m'
INFO='\033[1;36m'
DANGER='\033[1;97m\033[41m'

# No Color
NC='\033[0m'

function timeStamp() {
    echo $(date +"%T")
}

function info() {
    echo -e "$(timeStamp) ${INFO}$1${NC}"
}

function success() {
    echo -e "$(timeStamp) ${SUCCESS}$1${NC}"
}

function warning() {
    echo -e "$(timeStamp) ${WARNING}$1${NC}"
}

function danger() {
    echo -e "$(timeStamp) ${DANGER}$1${NC}"
    exit 1
}