#!/bin/bash

source .env
source app/constants
source app/functions

dotenv

# Start backup process

success "Start backup process"

currentVersion=$(php -r "include '${APPLICATION_PATH}/config/settings.inc.php';echo _PS_VERSION_;")
if [ "$currentVersion" == "$PRESTASHOP_NEW_VERSION" ]; then
    danger "You are trying to backup the already upgraded $PRESTASHOP_NEW_VERSION version"
    exit 1
else
    success "Backing up the current version"
fi

# Creating backup directories
mkdir -p "$backupPath/files"

# Rsync to backup files
rsync -azv \
    --exclude 'cache/cachefs' \
    --exclude 'themes/*/cache' \
    --exclude 'log' \
    --exclude 'var' \
    "$APPLICATION_PATH/" "$backupPath/files"

if [[ $? == 0 ]]; then
    success "Code backup completed"
else
    danger "rsync failed with exit code $?"
    exit 1
fi

if [[ -n $DATABASE_HOST && -n $DATABASE_USER && -n $DATABASE_PASSWORD && -n $DATABASE_NAME ]]; then

    # Database backup
    mysqldump -h$DATABASE_HOST -u$DATABASE_USER -p$DATABASE_PASSWORD $DATABASE_NAME > $backupPath/database.sql

    if [[ $? == 0 ]]; then
        success "Database backup created"
    else
        warning "Database dump failed with exit code $?"
        exit 1
    fi

    success "Backup process completed successfully."
else
    danger "Database parameters are not set."
fi
